// Date: 5/17/2014 10:07:14 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.FinalKill.Machinery_Craft.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelMacerator extends ModelBase
{
  //fields
    ModelRenderer Core;
    ModelRenderer Side1;
    ModelRenderer Side2;
    ModelRenderer Side3;
    ModelRenderer Side4;
  public  ModelRenderer BladeAxis;
 public ModelRenderer Blade1;
  
  public ModelMacerator()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      Core = new ModelRenderer(this, 0, 0);
      Core.addBox(0F, 0F, 0F, 16, 15, 16);
      Core.setRotationPoint(-8F, 9F, -8F);
      Core.setTextureSize(128, 128);
      Core.mirror = true;
      setRotation(Core, 0F, 0F, 0F);
      Side1 = new ModelRenderer(this, 0, 32);
      Side1.addBox(0F, 0F, 0F, 1, 1, 10);
      Side1.setRotationPoint(-5F, 8F, -5F);
      Side1.setTextureSize(128, 128);
      Side1.mirror = true;
      setRotation(Side1, 0F, 0F, 0F);
      Side2 = new ModelRenderer(this, 0, 32);
      Side2.addBox(0F, 0F, 0F, 1, 1, 10);
      Side2.setRotationPoint(4F, 8F, -5F);
      Side2.setTextureSize(128, 128);
      Side2.mirror = true;
      setRotation(Side2, 0F, 0F, 0F);
      Side3 = new ModelRenderer(this, 64, 0);
      Side3.addBox(0F, 0F, 0F, 8, 1, 1);
      Side3.setRotationPoint(-4F, 8F, -5F);
      Side3.setTextureSize(128, 128);
      Side3.mirror = true;
      setRotation(Side3, 0F, 0F, 0F);
      Side4 = new ModelRenderer(this, 64, 0);
      Side4.addBox(0F, 0F, 0F, 8, 1, 1);
      Side4.setRotationPoint(-4F, 8F, 4F);
      Side4.setTextureSize(128, 128);
      Side4.mirror = true;
      setRotation(Side4, 0F, 0F, 0F);
      BladeAxis = new ModelRenderer(this, 104, 66);
      BladeAxis.addBox(0F, 0F, 0F, 2, 2, 2);
      BladeAxis.setRotationPoint(-1F, 7F, -1F);
      BladeAxis.setTextureSize(128, 128);
      BladeAxis.mirror = true;
      setRotation(BladeAxis, 0F, 0F, 0F);
      Blade1 = new ModelRenderer(this, 0, 53);
      Blade1.addBox(0F, 0F, 0F, 2, 0, 8);
      Blade1.setRotationPoint(-1F, 7F, 0F);
      Blade1.setTextureSize(128, 128);
      Blade1.mirror = true;
      setRotation(Blade1, 0F, 0F, 0F);
  }

  
  public void renderModel(float f){
	  Core.render(f);
	    Side1.render(f);
	    Side2.render(f);
	    Side3.render(f);
	    Side4.render(f);
	    BladeAxis.render(f);
	    Blade1.renderWithRotation(f);
	  
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Core.render(f5);
    Side1.render(f5);
    Side2.render(f5);
    Side3.render(f5);
    Side4.render(f5);
    BladeAxis.render(f5);
    Blade1.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
