// Date: 4/26/2014 9:32:32 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.FinalKill.Machinery_Craft.model;

import net.minecraft.client.model.*;
import net.minecraft.entity.Entity;

public class ModelTrashcan extends ModelBase
{
  //fields
    ModelRenderer Side1;
    ModelRenderer Side2;
    ModelRenderer Side3;
    ModelRenderer Side4;
    ModelRenderer Bottom;
  
  public ModelTrashcan()
  {
	  textureWidth = 64;
	    textureHeight = 32;
	    
	      Bottom = new ModelRenderer(this, 0, 0);
	      Bottom.addBox(0F, 0F, 0F, 8, 1, 8);
	      Bottom.setRotationPoint(-4F, 23F, -4F);
	      Bottom.setTextureSize(64, 32);
	      Bottom.mirror = true;
	      setRotation(Bottom, 0F, 0F, 0F);
	      Side1 = new ModelRenderer(this, 0, 0);
	      Side1.addBox(0F, 0F, 0F, 1, 8, 8);
	      Side1.setRotationPoint(-5F, 15F, -4F);
	      Side1.setTextureSize(64, 32);
	      Side1.mirror = true;
	      setRotation(Side1, 0F, 0F, -0.1487195F);
	      Side2 = new ModelRenderer(this, 0, 0);
	      Side2.addBox(0F, 0F, 0F, 8, 8, 1);
	      Side2.setRotationPoint(-4F, 15F, 4F);
	      Side2.setTextureSize(64, 32);
	      Side2.mirror = true;
	      setRotation(Side2, -0.1487195F, 0F, 0F);
	      Side3 = new ModelRenderer(this, 0, 0);
	      Side3.addBox(0F, 0F, 0F, 1, 8, 8);
	      Side3.setRotationPoint(4F, 15F, -4F);
	      Side3.setTextureSize(64, 32);
	      Side3.mirror = true;
	      setRotation(Side3, 0F, 0F, 0.1487195F);
	      Side4 = new ModelRenderer(this, 0, 0);
	      Side4.addBox(0F, 0F, 0F, 8, 8, 1);
	      Side4.setRotationPoint(-4F, 15F, -5F);
	      Side4.setTextureSize(64, 32);
	      Side4.mirror = true;
	      setRotation(Side4, 0.1487144F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Side1.render(f5);
    Side2.render(f5);
    Side3.render(f5);
    Side4.render(f5);
    Bottom.render(f5);
  }
  
  public void renderModel(float f5){
	  Side1.render(f5);
	    Side2.render(f5);
	    Side3.render(f5);
	    Side4.render(f5);
	    Bottom.render(f5);
	  
  }
  
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
  }

}
