// Date: 5/24/2014 1:23:46 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.FinalKill.Machinery_Craft.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelRainCollector extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
  public ModelRenderer water;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
  
  public ModelRainCollector()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 12, 14, 1);
      Shape1.setRotationPoint(-6F, 10F, 5F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 26, 0);
      Shape2.addBox(0F, 0F, 0F, 1, 14, 10);
      Shape2.setRotationPoint(-6F, 10F, -5F);
      Shape2.setTextureSize(128, 64);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 26, 0);
      Shape3.addBox(0F, 0F, 0F, 1, 14, 10);
      Shape3.setRotationPoint(5F, 10F, -5F);
      Shape3.setTextureSize(128, 64);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 0, 0);
      Shape4.addBox(0F, 0F, 0F, 12, 14, 1);
      Shape4.setRotationPoint(-6F, 10F, -6F);
      Shape4.setTextureSize(128, 64);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      water = new ModelRenderer(this, 0, 24);
      water.addBox(0F, 0F, 0F, 10, 12, 10);
      water.setRotationPoint(-5F, 11F, -5F);
      water.setTextureSize(128, 64);
      water.mirror = true;
      setRotation(water, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 24, 47);
      Shape5.addBox(0F, 0F, 0F, 10, 1, 10);
      Shape5.setRotationPoint(-5F, 23F, -5F);
      Shape5.setTextureSize(128, 64);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 64, 20);
      Shape6.addBox(0F, 0F, 0F, 10, 1, 10);
      Shape6.setRotationPoint(-5F, 10F, -5F);
      Shape6.setTextureSize(128, 64);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    water.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void renderModel(float f){
  Shape1.render(f);
    Shape2.render(f);
    Shape3.render(f);
    Shape4.render(f);
    water.render(f);
    Shape5.render(f);
    Shape6.render(f);
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
